[package]
name = "yfokon"
version = "0.9.1"
description = "Application de gestion de taches et listes"
authors = ["marvideomc.pro@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "yfokon_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-process = "2.3"
tauri-plugin-fs = "2.4"
tauri-plugin-dialog = "2.3"
tauri-plugin-notification = "2.3"
tauri-plugin-sql = { version = "2.3", features = ["sqlite"] }
tauri-plugin-opener = "2.5"
tauri-plugin-http = "2.5"
tauri-plugin-store = "2"
dirs-next = "=2.0.0"
# x11 = "2.21.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state = "2"
